services:

  autonomy_datasets:
    image: ghcr.io/thinking-cars/autonomy_datasets:latest_init_ci
    command: ros2 launch autonomy_datasets autonomy_datasets.launch.py rviz:=no dataset:=nuscenes
    environment:
      ZENOH_CONFIG_OVERRIDE: routing/router/peers_failover_brokering=true;listen/endpoints=["tcp/[::]:7447"]
    volumes:
      - $DATASET_DIR:/datasets
  
  autonomy_benchmarks:
    image: ghcr.io/thinking-cars/autonomy_benchmarks-internal:latest_init_ci
    command: ros2 launch autonomy_benchmarks autonomy_benchmarks.launch.py benchmark:=nuscenes_lidar_object_detection
    environment:
      ZENOH_CONFIG_OVERRIDE: connect/endpoints=["tcp/autonomy_datasets:7447"]
