name: ${USER}-autonomy-benchmarks

services:

  autonomy_benchmarks:
    extends:
      file: docker-compose.yml
      service: autonomy_benchmarks
    image: ghcr.io/thinking-cars/autonomy_benchmarks:latest-dev
    command: sleep infinity
    volumes:
      - .:/docker-ros/ws/src/target
      - ${HOME}/.claude:/root/.claude

  autonomy_datasets:
    extends:
      file: docker-compose.yml
      service: autonomy_datasets
    # image: ghcr.io/thinking-cars/autonomy_datasets:latest-dev
    # command: sleep infinity
    # volumes:
    #   - ../autonomy_datasets:/docker-ros/ws/src/target
    #   - ${HOME}/.claude:/root/.claude

  autoware_lidar_centerpoint:
    extends:
      file: docker-compose.yml
      service: autoware_lidar_centerpoint

  focalformer3d-detector:
    extends:
      file: docker-compose.yml
      service: focalformer3d-detector
