services:

  zenoh-router:
    extends:
      file: docker-compose.yml
      service: zenoh-router

  autonomy_datasets:
    extends:
      file: docker-compose.yml
      service: autonomy_datasets
    image: ghcr.io/thinking-cars/autonomy_datasets:latest-dev_init_ci
    command: sleep infinity
    volumes:
      - ../autonomy_datasets:/docker-ros/ws/src/target
  
  autonomy_benchmarks:
    extends:
      file: docker-compose.yml
      service: autonomy_benchmarks
    image: ghcr.io/thinking-cars/autonomy_benchmarks-internal:latest-dev_init_ci
    command: sleep infinity
    volumes:
      - .:/docker-ros/ws/src/target
