name: ${USER}-autonomy-benchmarks

services:

  autonomy_datasets:
    extends:
      file: docker-compose.yml
      service: autonomy_datasets
  
  autonomy_benchmarks_object_tracking:
    extends:
      file: docker-compose.yml
      service: autonomy_benchmarks_object_tracking
    image: ghcr.io/thinking-cars/autonomy_benchmarks-internal:latest-dev_init_ci
    command: sleep infinity
    volumes:
      - .:/docker-ros/ws/src/target
      - ${HOME}/.claude:/root/.claude

  autoware_multi_object_tracker:
    extends:
      file: docker-compose.yml
      service: autoware_multi_object_tracker
