apiVersion: v2
name: autonomy-evaluation
version: 1.0.0
appVersion: 1.0.0
description: Metrics-based evaluation of automated driving modules, generating the evidence for benchmarking automated driving deployments
dependencies:
  - repository: oci://ghcr.io/openads-project/openads-helm
    name: openadservice
    version: 1.2.0
